---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Installing software
    - name: module-02
      label: Logging in and navigating Web Console
    - name: module-03
      label: Configuring and enabling session recording
    - name: module-04
      label: Reviewing the configuration
    - name: module-05
      label: Recording a session
    - name: module-06
      label: Reviewing a recorded session in Web Console
    - name: module-07
      label: Reviewing a recorded session from the command-line
tabs:
  - name: ">_ Terminal"
    port: 443
    path: /tty1
    user: root
    host: rhel
